export const experienceData = [
    {
        id: '1',
        company: 'Nexus digital agency',
        position: 'InfoPage.experience.position1',
        period: '2026.02 - ',
        periodEnd: 'InfoPage.experience.present',
        description: 'InfoPage.experience.description1',
        projects: 1,
        technologies: [
            'WordPress',
            'JavaScript',
            'PHP',
            'Custom Plugins',
            'Performance Optimization',
        ],
    },
    {
        id: '2',
        company: 'Walterwakefield',
        position: 'InfoPage.experience.position2',
        period: '2025.11 - ',
        periodEnd: 'InfoPage.experience.present',
        description: 'InfoPage.experience.description2',
        projects: 30,
        technologies: [
            'WordPress',
            'ACF',
            'Elementor',
            'Avada',
            'Hosting',
            'Data Migration',
        ],
    },
    {
        id: '3',
        company: 'PixoPhone',
        position: 'InfoPage.experience.position3',
        period: '2025.04 - 2025.11',
        description: 'InfoPage.experience.description3',
        projects: 1,
        technologies: [
            'OpenCart',
            'PHP',
            'MySQL',
            'Database Optimization',
            'Custom Panels',
        ],
    },
    {
        id: '4',
        company: 'SlutCraft',
        position: 'InfoPage.experience.position4',
        period: '2023.07 - ',
        periodEnd: 'InfoPage.experience.present',
        description: 'InfoPage.experience.description4',
        projects: 1,
        technologies: [
            'React.js',
            'UI/UX',
            'Performance Optimization',
            'SEO',
            'Localization',
        ],
    },
    {
        id: '5',
        company: 'Freelance',
        position: 'InfoPage.experience.position5',
        period: '2023.05 - 2025.04',
        description: 'InfoPage.experience.description5',
        projects: 30,
        technologies: [
            'WordPress',
            'React.js',
            'JavaScript',
            'Custom Solutions',
            'Redesign',
        ],
    },
    {
        id: '6',
        company: 'Meat Hammer Studio',
        position: 'InfoPage.experience.position6',
        period: '2021.10 - 2023.05',
        description: 'InfoPage.experience.description6',
        projects: 5,
        technologies: [
            'Jira',
            'Project Management',
            'Time Tracking',
            'Process Optimization',
        ],
    },
    {
        id: '7',
        company: 'Meat Hammer Studio',
        position: 'InfoPage.experience.position7',
        period: '2019.09 - 2021.10',
        description: 'InfoPage.experience.description7',
        projects: 4,
        technologies: [
            'HTML',
            'CSS',
            'JavaScript',
            'WordPress',
            'Pixel Perfect',
        ],
    },
];

export default experienceData;
