export const skills = [
    {
        id: '1',
        title: 'HTML',
        level: '5',
        category: 'frontend',
        experience: '5+ років',
    },
    {
        id: '2',
        title: 'CSS',
        level: '5',
        category: 'frontend',
        experience: '5+ років',
    },
    {
        id: '3',
        title: 'JavaScript',
        level: '5',
        category: 'frontend',
        experience: '5+ років',
    },
    {
        id: '4',
        title: 'React',
        level: '4',
        category: 'frontend',
        experience: '4+ роки',
    },
    {
        id: '5',
        title: 'Vue.js',
        level: '3',
        category: 'frontend',
        experience: '2+ роки',
    },
    {
        id: '6',
        title: 'TypeScript',
        level: '4',
        category: 'frontend',
        experience: '3+ роки',
    },
    {
        id: '7',
        title: 'SCSS',
        level: '5',
        category: 'frontend',
        experience: '4+ роки',
    },
    {
        id: '8',
        title: 'Tailwind CSS',
        level: '4',
        category: 'frontend',
        experience: '2+ роки',
    },
    {
        id: '9',
        title: 'Node.js',
        level: '4',
        category: 'backend',
        experience: '3+ роки',
    },
    {
        id: '10',
        title: 'PHP',
        level: '4',
        category: 'backend',
        experience: '4+ роки',
    },
    {
        id: '11',
        title: 'Express',
        level: '4',
        category: 'backend',
        experience: '3+ роки',
    },
    {
        id: '12',
        title: 'MongoDB',
        level: '3',
        category: 'backend',
        experience: '2+ роки',
    },
    {
        id: '13',
        title: 'MySQL',
        level: '4',
        category: 'backend',
        experience: '3+ роки',
    },
    {
        id: '14',
        title: 'Git',
        level: '5',
        category: 'tools',
        experience: '5+ років',
    },
    {
        id: '15',
        title: 'Docker',
        level: '3',
        category: 'tools',
        experience: '2+ роки',
    },
    {
        id: '16',
        title: 'Webpack',
        level: '4',
        category: 'tools',
        experience: '3+ роки',
    },
    {
        id: '17',
        title: 'Vite',
        level: '4',
        category: 'tools',
        experience: '2+ роки',
    },
    {
        id: '18',
        title: 'Figma',
        level: '4',
        category: 'tools',
        experience: '3+ роки',
    },
    {
        id: '19',
        title: 'Photoshop',
        level: '3',
        category: 'tools',
        experience: '4+ роки',
    },
    {
        id: '20',
        title: 'WordPress',
        level: '5',
        category: 'other',
        experience: '5+ років',
    },
];

export default skills;
